controller_frequency: 3.0
recovery_behavior_enabled: true
clearing_rotation_allowed: false

TrajectoryPlannerROS:
   max_vel_x: 1.3 # 5km/h=1.3m/s
   min_vel_x: 0.1
   max_vel_y: 0.0  # zero for a differential drive robot
   min_vel_y: 0.0
   max_vel_theta: 1.0
   min_vel_theta: -1.0
   min_in_place_vel_theta: 0.5
   max_rotation_vel: 2.0
   min_in_place_rotation_vel: 0.5
   escape_vel: -0.1
   acc_lim_x: 1.5
   acc_lim_y: 0.0  # zero for a differential drive robot
   acc_lim_theta: 2.0

   holonomic_robot: false
   yaw_goal_tolerance: 0.4 # about 24 degrees
   xy_goal_tolerance: 0.5  # 50 cm
   latch_xy_goal_tolerance: false
   pdist_scale: 0.6 # default 0.8
   gdist_scale: 0.8 # default 0.4
   meter_scoring: false

   heading_lookahead: 1.5
   heading_scoring: true
   heading_scoring_timestep: 0.5
   occdist_scale: 0.05
   oscillation_reset_dist: 0.05
   publish_cost_grid_pc: false
   # prune_plan: true

   sim_time: 1.7
   sim_granularity: 0.05
   angular_sim_granularity: 0.05
   vx_samples: 8
   vy_samples: 0  # zero for a differential drive robot
   vtheta_samples: 20
   dwa: true
   simple_attractor: false
