obstacle_range: 0.8
raytrace_range: 0.8
footprint: [[2.5, 2.0], [2.5, -2.0], [-2.5, -2.0], [-2.5, 2.0]]
footprint_inflation: 0.5
#robot_radius: 0.175
inflation_radius: 0.5
max_obstacle_height: 0.93 # 37 inch
min_obstacle_height: 0.43 # 17 inch
observation_sources: scan
scan: {data_type: LaserScan, topic: /laser/scan, marking: true, clearing: true, expected_update_rate: 0}
