controller_frequency: 3.0
recovery_behavior_enabled: false
clearing_rotation_allowed: false
# conservative_reset_dist: 3.0
planner_patience: 60
controller_patience: 60
# oscillation_timeout: 60
# oscillation_distance: 1.0
# planner_frequency: 3.0

TrajectoryPlannerROS:
   max_vel_x: 2 # 5km/h=1.3m/s
   min_vel_x: 0.2
   max_vel_y: 0.0  # zero for a differential drive robot
   min_vel_y: 0.0
   max_vel_theta: 1.5
   min_vel_theta: -1.5
   min_in_place_vel_theta: 1.5
   min_in_place_rotation_vel: 1.5
   escape_vel: -1.0
   acc_lim_x: 0.8
   acc_lim_y: 0.0  # zero for a differential drive robot
   acc_lim_theta: 1.0

   holonomic_robot: false
   yaw_goal_tolerance: 0.2 # about 24 degrees
   xy_goal_tolerance: 2  # 50 cm
   latch_xy_goal_tolerance: false
   pdist_scale: 0.8 # default 0.8
   gdist_scale: 0.4 # default 0.4
   meter_scoring: true

   heading_lookahead: 5.5
   heading_scoring: true
   heading_scoring_timestep: 0.5
   occdist_scale: 0.05
   oscillation_reset_dist: 0.05
   publish_cost_grid_pc: false
   prune_plan: true

   sim_time: 20
   sim_granularity: 0.1
   angular_sim_granularity: 0.05
   vx_samples: 8
   vy_samples: 0  # zero for a differential drive robot
   vtheta_samples: 20
   dwa: true
   simple_attractor: true
